project_name: portal
before:
  hooks:
    - go mod tidy
builds:
  - id: "portal-client-app"
    main: ./cmd/portal
    binary: portal
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
      - openbsd
      - dragonfly
    ldflags: -s -w -X main.version={{.Version}} -X main.revision={{.ShortCommit}} -X main.date={{.Date}}
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      386: x86_32
      amd64: x86_64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      dragonfly: DragonFlyBSD
    files:
      - LICENSE
      - CREDITS
nfpms:
  - formats:
      - apk
      - deb
      - rpm
    vendor: "portal"
    description: "Portal is a quick and easy command-line file transfer utility from any computer to another 🖥️ 🌌 💻"
    license: "MIT"
    package_name: portal
    replacements:
      386: x86_32
      amd64: x86_64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      dragonfly: DragonFlyBSD
brews:
  - tap:
      owner: ZinoKader
      name: homebrew-portal
    folder: Formula
    homepage: "https://github.com/ZinoKader/portal"
    description: "Portal is a quick and easy command-line file transfer utility from any computer to another 🖥️ 🌌 💻"
    license: "MIT"
release:
  prerelease: auto
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
