name: ci

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - develop
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Go setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: -v --timeout=5m

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Go setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Go setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out -failfast ./...

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true
